disabled_rules:
  - identifier_name
  - trailing_comma

line_length:
  - 300 # warning
  - 400 # error

function_body_length:
  - 80 # warning
  - 100 # error

cyclomatic_complexity:
  - 50 # warning
  - 60 # error

function_parameter_count:
  - 8 # warning
  - 10 # error
